'use client';

import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [code, setCode] = useState("");
  const [wisdom, setWisdom] = useState("");
  const [image, setImage] = useState("");

  async function generateWisdom() {
    try {
      const response = await axios.post('/api/generate-comments', { code });
      setWisdom(response.data.comments);
      console.log(response.data.comments);  // Log the comments for debugging
      await generateImage(response.data.comments);
    } catch (error) {
      console.log("Error generating comments: ", error);
    }
  }

  async function generateImage(wisdom) {
    try {
      const response = await axios.post('/api/generate-image', { prompt: wisdom });
      setImage(response.data.imageUrl);
    } catch (error) {
      console.log("Error generating image: ", error);
    }
  }

  return (
    <div>
      <h1>Dark Fantasy Dev</h1>
      <p>Speak to the Wizard...</p>
      <textarea
        value={code}
        onChange={(event) => setCode(event.target.value)}
        placeholder="Offer a code snippet to begin your dark fantasy adventure..."
      />
      <button onClick={generateWisdom}>Enter</button>
      <textarea
        value={wisdom}
        readOnly
        placeholder="Wisdom will appear here..."
      />
      <p>Visualize your journey</p>
      {image && <img src={image} alt="Generated by DALL-E" />}
    </div>
  );
}

